//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PageCloud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int taxInvoice { get; set; }
        public System.DateTime invoiceDate { get; set; }
        public System.DateTime dueDate { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<bool> invoiceStatus { get; set; }
        public Nullable<int> domainID { get; set; }
    
        public virtual Domain Domain { get; set; }
    }
}
