//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PageCloud.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PageCloudEntities : DbContext
    {
        public PageCloudEntities()
            : base("name=PageCloudEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Domain> Domains { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual int SP_Insert_User(string userName, string userSurname, string userEmail, string userPassword, Nullable<System.DateTime> registerDate, string phone, string userAddress, string city, string postalCode, string idno, string gender, string userRole)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            var userSurnameParameter = userSurname != null ?
                new ObjectParameter("userSurname", userSurname) :
                new ObjectParameter("userSurname", typeof(string));
    
            var userEmailParameter = userEmail != null ?
                new ObjectParameter("userEmail", userEmail) :
                new ObjectParameter("userEmail", typeof(string));
    
            var userPasswordParameter = userPassword != null ?
                new ObjectParameter("userPassword", userPassword) :
                new ObjectParameter("userPassword", typeof(string));
    
            var registerDateParameter = registerDate.HasValue ?
                new ObjectParameter("registerDate", registerDate) :
                new ObjectParameter("registerDate", typeof(System.DateTime));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var userAddressParameter = userAddress != null ?
                new ObjectParameter("userAddress", userAddress) :
                new ObjectParameter("userAddress", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var postalCodeParameter = postalCode != null ?
                new ObjectParameter("postalCode", postalCode) :
                new ObjectParameter("postalCode", typeof(string));
    
            var idnoParameter = idno != null ?
                new ObjectParameter("idno", idno) :
                new ObjectParameter("idno", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            var userRoleParameter = userRole != null ?
                new ObjectParameter("userRole", userRole) :
                new ObjectParameter("userRole", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Insert_User", userNameParameter, userSurnameParameter, userEmailParameter, userPasswordParameter, registerDateParameter, phoneParameter, userAddressParameter, cityParameter, postalCodeParameter, idnoParameter, genderParameter, userRoleParameter);
        }
    }
}
